from pyspark.sql.types import *

csvSchema = StructType([
  StructField("Year", IntegerType()),
  StructField("Month", IntegerType()),
  StructField("DayofMonth", IntegerType()),
  StructField("DayOfWeek", IntegerType()),
  StructField("DepTime", IntegerType()),
  StructField("CRSDepTime", IntegerType()),
  StructField("ArrTime", IntegerType()),
  StructField("CRSArrTime", IntegerType()),
  StructField("UniqueCarrier", StringType()),
  StructField("FlightNum", IntegerType()),
  StructField("TailNum", StringType()),
  StructField("ActualElapsedTime", IntegerType()),
  StructField("CRSElapsedTime", IntegerType()),
  StructField("AirTime", StringType()),
  StructField("ArrDelay", IntegerType()),
  StructField("DepDelay", IntegerType()),
  StructField("Origin", StringType()),
  StructField("Dest", StringType()),
  StructField("Distance", IntegerType()),
  StructField("TaxiIn", StringType()),
  StructField("TaxiOut", StringType()),
  StructField("Cancelled", IntegerType()),
  StructField("CancellationCode", StringType()),
  StructField("Diverted", StringType()),
  StructField("CarrierDelay", StringType()),
  StructField("WeatherDelay", StringType()),
  StructField("NASDelay", StringType()),
  StructField("SecurityDelay", StringType()),
  StructField("LateAircraftDelay", StringType())
 ])
